baseURL = "https://bundestag.ai/"
languageCode = "de-de"
title = "BundestagAI"
theme = "Agnes"

[params]
dateFormat = "Jan 2, 2023"
authorName = "Ported to Hugo by Debashish"
google_analytics_id = "GA-"

[menu]
[[menu.main]]
Name = "Projekt"
URL = "#"
weight = 1

[[menu.main]]
Name = "Quellcode"
URL = "#"
weight = 2

[[menu.main]]
Name = "Impressum"
URL = "#"
weight = 3

[params.social]
LinkedInURL = "https://linkedin.com/company/bundestagai"
GitHubURL = "https://github.com/organization/bundestagAI"

[params.content]
LeadTitle = "bundestag.ai"
LeadDescription = "Dein intelligentes Portal zum deutschen Bundestag"
ButtonCaption = "Mehr erfahren"
ButtonURL = "/about"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
FeatureTitle = "NORMan"
FeatureDescription = "Chatte mit einer KI, die mit einem von dir gewählten Gesetz angereichert wurde"
FeatureImage = "images/feature-1.png"
FeatureLink = "https://norman.bundestag.ai/"

[[params.feature]]
FeatureTitle = "AskTheDIP"
FeatureDescription = "Chatte mit einer KI, die mit allen Drucksachen und Plenarprotokollen des DIP angereichert wurde"
FeatureImage = "images/feature-2.png"
FeatureLink = "https://askthedip.bundestag.ai/"

[[params.feature]]
FeatureTitle = "mDB"
FeatureDescription = "Chatte mit einer KI, die mit Profilen aller Abgeordneten angereichert wurde"
FeatureImage = "images/feature-3.png"
FeatureLink = "https://mdb.bundestag.ai/"

[[params.feature]]
FeatureTitle = "pReSSe"
FeatureDescription = "Chatte mit einer KI, die mit aktuellen Presse- und Kurzmeldungen angereichert wurde"
FeatureImage = "images/feature-4.png"
FeatureLink = "https://presse.bundestag.ai/"

[[params.pricing]]
	PricingTitle = "Free"
	PricingRate = "0"	
	ButtonCaption = "Direkt Loslegen"
	[[params.pricing.Features]]
		Description = "Zugang zu allen Tools"
	[[params.pricing.Features]]
		Description = "Keine Accounts / Authorisierung"
    [[params.pricing.Features]]
		Description = "Bring Your Own API Key"
	[[params.pricing.Features]]
		Description = "Kein Support"

[[params.pricing]]
	PricingTitle = "Business"
	PricingRate = "299"
	ButtonCaption = "Get Early Access"
	[[params.pricing.Features]]
		Description = "Zugang zu allen Tools"
	[[params.pricing.Features]]
		Description = "5 Accounts"
    [[params.pricing.Features]]
		Description = "10M Token"
	[[params.pricing.Features]]
		Description = "E-Mail Support"	
	
[[params.pricing]]
	PricingTitle = "Enterprise"
	PricingRate = "4900"
	ButtonCaption = "Get Early Access"
	[[params.pricing.Features]]
		Description = "Zugang zu allen Tools"
	[[params.pricing.Features]]
		Description = "100 Accounts"
    [[params.pricing.Features]]
		Description = "100M Token"
	[[params.pricing.Features]]
		Description = "24/7 Live Support"
